### ISSUE TITLE
Positioning changes/bug?

### ISSUE THREAD

**Issue by PatientAsian** [erversteeg/Frost-Hp-Run#2]
First of all, thank you for your work, really cool plugin!

I was wondering why the display isn't recognized as a movable UI object like many others (as in, double Alt-press doesn't make it movable). 

I have no issue with with the way you programmed the positioning options, but for some reason it resets when I log back in, and additionally, I can't seem to make it snap away to anything other than the top left corner, regardless of the anchor position.

It's almost as if its anchors are limited to an invisible box that takes up maybe a 1/4th of the screen. Since negative values aren't accepted, I can't get it below the center of my screen which is where I'd prefer it to be.

Is this something you'd be willing to add?
Thanks for adding color customization support by the way! :)

**Comment by erversteeg** [comment]
Sure I can add this feature in. Those anchors are based upon constant values in the Runelite API that are based upon something like the top left corner of the inventory and the plugin adds the size of the inventory to get the absolute bottom-right hand corner of the screen. It sounds like maybe those values are different in your setup. Negative values should allow you to set and keep a good position for the bar. 

In the meantime are you by chance able to get it positioned where you want by setting top-left anchor with higher offset values?

Not sure why it's not saving configuration options. If you are able to get some configuration options to save like hue then it may possibility be how Runelite exited.

**Comment by PatientAsian** [comment]
Update: I have now realized that the plugin seems to be tied to my inventory, which is why it "appears" to be resetting on login. In actuality, I just don't have my inventory open.

If I drag the inventory around, the plugin widget will follow along, as if it's snapped to it. The Top/Bottom etc. anchor points work within the vicinity of the inventory, but I couldn't find any option that changed this behavior.

**Comment by erversteeg** [comment]
Thanks for the info. Instead of negative offsets, an option to turn the default anchoring setting off so the offset X and Y apply in an absolute sense from the upper left hand corner should fix the issue.

**Comment by erversteeg** [comment]
Added an additional option "None" to Anchor. Hopefully this resolves the positioning issue for you. Update is pending right now on Plugin Hub, it can take up to few weeks to go live but a small change like this may go through faster.

**Comment by erversteeg** [comment]
This change is now live.
